# Generated by Django 3.0.7 on 2020-06-19 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='round_name',
            field=models.CharField(default=datetime.date(2020, 6, 18), max_length=140),
            preserve_default=False,
        ),
    ]
