# Generated by Django 3.0.7 on 2020-06-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0005_auto_20200619_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_answer',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
