# Generated by Django 3.0.7 on 2020-06-21 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0006_team_answer_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_answer',
            name='scored',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(default=datetime.date(2020, 6, 20)),
        ),
    ]
