# Generated by Django 3.0.7 on 2020-06-24 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0007_auto_20200620_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='Friends Trivia!', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='double_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(default=datetime.date(2020, 6, 23)),
        ),
    ]
