# Generated by Django 3.0.7 on 2020-06-24 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0008_auto_20200623_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['round_num']},
        ),
    ]
