# Generated by Django 3.0.7 on 2020-06-24 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0008_auto_20200623_1857'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team_Answer',
            new_name='T_Answer',
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['round_num']},
        ),
    ]
