# Generated by Django 3.0.7 on 2020-06-24 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0009_auto_20200623_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(default=datetime.date(2020, 6, 24)),
        ),
        migrations.AlterField(
            model_name='game',
            name='password',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
