# Generated by Django 3.0.7 on 2020-06-25 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0010_auto_20200624_0016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['game', 'score']},
        ),
    ]
