# Generated by Django 3.0.7 on 2020-06-29 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0012_auto_20200625_0142'),
        ('trivia', '0012_auto_20200625_0653'),
    ]

    operations = [
    ]
