# Generated by Django 3.0.7 on 2020-06-29 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0013_merge_20200628_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='t_answer',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(default=datetime.date(2020, 6, 28)),
        ),
    ]
