# Generated by Django 2.2.7 on 2020-06-29 02:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0014_auto_20200628_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(default=datetime.date(2020, 6, 29)),
        ),
    ]
