# Generated by Django 3.0.7 on 2020-07-10 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0015_auto_20200629_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='description',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(default=datetime.date(2020, 7, 9)),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=999),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=9999),
        ),
    ]
